/**
  ******************************************************************************
  * @file      startup_stm32f407vgtx.s
  * @author    Auto-generated by STM32CubeIDE
  * @Abstract : Startup script for STM32F407VGTx Device
  * @version   V1.0.0
  * @date      2020-02-14
  ******************************************************************************
  *
  * OVERVIEW FOR BEGINNERS:
  * ========================
  * This file is the very first code that runs when your STM32 microcontroller
  * powers on or resets. Before your C code (main()) can run, several things
  * must be set up at the hardware level. This file does those things:
  *
  *   1. Sets up the stack pointer (where function call data lives in RAM)
  *   2. Copies initialized global variables from Flash (permanent storage)
  *      into RAM (working memory), because RAM loses its contents on power loss
  *   3. Zeroes out uninitialized global variables (the BSS segment)
  *   4. Calls SystemInit() to configure clocks
  *   5. Calls __libc_init_array() to run C++ static constructors
  *   6. Jumps to your main() function
  *
  * It also defines the "vector table" — a lookup table of function pointers
  * that tells the hardware WHERE to jump when an interrupt or exception fires.
  *
  * This file is written in ARM Thumb assembly. You don't need to edit it
  * unless you are doing very low-level customization.
  */

/* ============================================================================
 * ASSEMBLER DIRECTIVES
 * These are instructions TO the assembler (the program that converts this
 * text into machine code), not instructions that run on the chip itself.
 * ============================================================================ */

.syntax unified      /* Use "unified" ARM/Thumb syntax — a modern syntax that
                        lets you write both ARM and Thumb instructions the
                        same way, instead of having two different styles. */

.cpu cortex-m4       /* Tell the assembler we're targeting the ARM Cortex-M4
                        core inside the STM32F407. This enables Cortex-M4
                        specific instructions. */

.fpu softvfp         /* "softvfp" = software floating point ABI with hardware
                        FPU registers. This means: use the hardware FPU unit
                        for calculations, but pass float arguments through
                        integer registers when calling functions.
                        The alternative is "hard" (hardfp) which passes floats
                        directly in FPU registers — slightly faster but
                        requires all libraries to be compiled the same way. */

.thumb               /* Generate Thumb-2 instructions (16/32-bit compact
                        encoding) rather than full 32-bit ARM instructions.
                        Cortex-M4 ONLY runs Thumb mode — it cannot execute
                        classic 32-bit ARM instructions at all. */

/* ============================================================================
 * GLOBAL SYMBOL EXPORTS
 * These lines make these two symbols visible to the linker and other files.
 * Without .global, a symbol is private to this file.
 * ============================================================================ */

.global g_pfnVectors   /* The interrupt vector table (defined later in this
                          file). The linker needs to find it to place it at
                          address 0x00000000 in Flash. */

.global Default_Handler /* A catch-all handler for any interrupt that doesn't
                           have a real implementation written yet. */

/* ============================================================================
 * LINKER SCRIPT SYMBOL REFERENCES
 * The .word directive places a 32-bit address literal into the output binary.
 * These symbols (starting with underscore) are NOT defined here — they are
 * defined in the linker script (.ld file) which knows the exact memory map
 * of this chip. The linker will fill in the actual addresses at link time.
 *
 * Think of this like declaring "extern" variables in C: we're telling the
 * assembler "these addresses exist somewhere, the linker will resolve them."
 * ============================================================================ */

.word _sidata  /* Source address in Flash where the initial values of
                  initialized global variables are stored.
                  ("si" = source of initialized data) */

.word _sdata   /* Start address in RAM where .data section begins.
                  ("s" = start, "data" = initialized globals/statics) */

.word _edata   /* End address in RAM where .data section ends.
                  ("e" = end) */

.word _sbss    /* Start address in RAM of the .bss section.
                  BSS = Block Started by Symbol — this is where uninitialized
                  global and static variables live. C standard says they must
                  start as zero, so we'll zero this region out explicitly. */

.word _ebss    /* End address in RAM of the .bss section. */


/* ============================================================================
 * RESET HANDLER
 * ============================================================================
 *
 * This is the entry point of your entire program. When the chip powers on
 * or is reset, the hardware automatically:
 *   1. Reads address 0x00000000 → loads it into the Stack Pointer (SP)
 *   2. Reads address 0x00000004 → loads it into the Program Counter (PC)
 *
 * Address 0x00000004 in the vector table contains the address of
 * Reset_Handler, so execution jumps here immediately after reset.
 *
 * .section .text.Reset_Handler
 *   Put this code in a special named section so the linker can place it
 *   correctly. The linker script will pull this into the .text region of Flash.
 *
 * .weak Reset_Handler
 *   "Weak" means: if another file defines a symbol with this same name,
 *   use that one instead and discard this one. This lets application code
 *   override the default startup behavior if needed.
 *
 * .type Reset_Handler, %function
 *   Tells the assembler (and debugger) that this symbol is a function,
 *   not just a data label. Important for correct stack unwinding in debuggers.
 */

  .section .text.Reset_Handler
  .weak Reset_Handler
  .type Reset_Handler, %function

Reset_Handler:

  /* --- Step 1: Initialize the Stack Pointer ---
   *
   * The stack is a region of RAM used to store:
   *   - Return addresses when calling functions
   *   - Local variables
   *   - Saved register values during interrupts
   *
   * On Cortex-M, the stack grows DOWNWARD in memory (from high address to low).
   * _estack is defined in the linker script as the TOP of RAM (highest address).
   * We load this address into SP (Stack Pointer register, also called r13).
   *
   * "ldr r0, =_estack" is a pseudo-instruction. The assembler generates a
   * PC-relative load from a literal pool — it's loading the 32-bit address
   * value of _estack into register r0.
   *
   * "mov sp, r0" copies that value into the actual Stack Pointer register.
   *
   * After this, any function call or interrupt will use this stack correctly.
   */
  ldr   r0, =_estack
  mov   sp, r0


  /* --- Step 2: Copy .data section from Flash to RAM ---
   *
   * WHY IS THIS NECESSARY?
   * Flash memory retains its contents when power is removed, but it's
   * read-only at runtime (you can't write to Flash during normal execution
   * without a special erase/write procedure). RAM is fast and writable,
   * but loses everything on power-off.
   *
   * When you write C code like:
   *     int myGlobal = 42;   // initialized global variable
   *
   * The value 42 must be stored somewhere permanently (Flash), but the
   * variable itself must live in RAM so it can be modified. The linker puts
   * the initial value (42) into a Flash region called .sidata, and reserves
   * a slot in RAM called .data. This startup code copies from .sidata → .data
   * before main() runs, so your globals have their correct initial values.
   *
   * The copy loop below:
   *   r0 = destination start (RAM: _sdata)
   *   r1 = destination end   (RAM: _edata)
   *   r2 = source start      (Flash: _sidata)
   *   r3 = byte offset counter (starts at 0, increments by 4 each iteration)
   *
   * We jump to LoopCopyDataInit first to check whether there's anything
   * to copy at all (handles the edge case of an empty .data section).
   */
  ldr r0, =_sdata    /* Load address of start of .data section in RAM */
  ldr r1, =_edata    /* Load address of end of .data section in RAM */
  ldr r2, =_sidata   /* Load address of initial values stored in Flash */
  movs r3, #0        /* r3 = 0 (byte offset, starts at beginning) */
  b LoopCopyDataInit /* Jump to the loop condition check first */

CopyDataInit:
  /* Loop body: copy one 32-bit word (4 bytes) per iteration */
  ldr r4, [r2, r3]   /* Load 4 bytes from Flash: address = r2 + r3 offset */
  str r4, [r0, r3]   /* Store those 4 bytes to RAM:  address = r0 + r3 offset */
  adds r3, r3, #4    /* Advance offset by 4 bytes (one word) */
                     /* "adds" sets condition flags (N, Z, C, V) — needed by bcc below */

LoopCopyDataInit:
  /* Loop condition: check if we've reached the end of .data */
  adds r4, r0, r3    /* r4 = current destination address (RAM base + offset) */
  cmp r4, r1         /* Compare current address against end-of-.data (_edata) */
  bcc CopyDataInit   /* BCC = Branch if Carry Clear = Branch if r4 < r1
                        i.e., loop back if we haven't reached the end yet.
                        When r4 >= r1, we fall through and the copy is done. */


  /* --- Step 3: Zero-fill the .bss section in RAM ---
   *
   * WHY IS THIS NECESSARY?
   * The C standard guarantees that uninitialized global and static variables
   * start at zero. For example:
   *     int counter;           // uninitialized global — must start as 0
   *     static int flag;       // uninitialized static — must start as 0
   *
   * The linker places these in a section called .bss (historically "Block
   * Started by Symbol"). Nothing is stored in Flash for .bss (there are no
   * initial values to store — they're all zero). We just need to zero out
   * that RAM region ourselves before main() runs.
   *
   * r2 = current address being zeroed (starts at _sbss)
   * r4 = end address (_ebss)
   * r3 = the value 0 (what we're writing)
   *
   * Same pattern as above: jump to condition check first.
   */
  ldr r2, =_sbss     /* Load start address of .bss in RAM */
  ldr r4, =_ebss     /* Load end address of .bss in RAM */
  movs r3, #0        /* r3 = 0 (the value to write everywhere) */
  b LoopFillZerobss  /* Jump to condition check first */

FillZerobss:
  /* Loop body: write one 32-bit zero per iteration */
  str  r3, [r2]      /* Store 0 into current address (r2 points to RAM) */
  adds r2, r2, #4    /* Advance pointer by 4 bytes */

LoopFillZerobss:
  /* Loop condition: have we zeroed everything up to _ebss? */
  cmp r2, r4         /* Compare current pointer against end of .bss */
  bcc FillZerobss    /* Loop back if r2 < r4 (not done yet) */


  /* --- Step 4: Initialize the system clock ---
   *
   * SystemInit() is a function provided by ST's CMSIS/HAL library (in
   * system_stm32f4xx.c). It configures the PLL (Phase-Locked Loop) and
   * clock prescalers to run the chip at its target frequency (up to 168 MHz
   * on the F407). Without this call, the chip runs from the slow internal
   * RC oscillator at 16 MHz with no PLL.
   *
   * "bl" = Branch with Link. It calls the function AND saves the return
   * address in the Link Register (LR / r14), so the function can return
   * here with "bx lr".
   */
  bl  SystemInit


  /* --- Step 5: Run C++ static constructors ---
   *
   * __libc_init_array() is part of the C runtime library (newlib).
   * It iterates over the .init_array section in Flash and calls every
   * function pointer stored there. The compiler places constructors for
   * global C++ objects there, as well as any functions marked with
   * __attribute__((constructor)) in C.
   *
   * If you're writing pure C with no global objects, this effectively does
   * nothing — but it's safe and correct to always call it.
   */
  bl __libc_init_array


  /* --- Step 6: Call main() ---
   *
   * Everything is now set up. Jump to the user's application entry point.
   * "bl main" is technically a function call (saves return address in LR),
   * which is correct — main() could theoretically return, though on a
   * bare-metal embedded system it normally never does.
   */
  bl main


  /* --- Step 7: Trap if main() ever returns ---
   *
   * On an embedded system, main() returning is almost always a bug —
   * there's nowhere sensible to go back to. This infinite loop prevents
   * the program counter from wandering into random memory and executing
   * garbage instructions, which could cause unpredictable hardware behavior.
   *
   * A debugger can detect the chip is stuck here by examining the PC register.
   */
LoopForever:
    b LoopForever     /* "b" = unconditional Branch — jumps back to itself forever */


  /* Tell the assembler the size of Reset_Handler (used by debuggers for
     stack unwinding and function boundary detection).
     "." means "current address", so this computes: current_addr - Reset_Handler_start */
  .size Reset_Handler, .-Reset_Handler


/* ============================================================================
 * DEFAULT INTERRUPT HANDLER
 * ============================================================================
 *
 * If an interrupt fires but no specific handler function has been written
 * for it, the weak alias mechanism (defined at the bottom of this file)
 * redirects it here. This handler just spins forever in an infinite loop.
 *
 * In practice, if you hit this handler unexpectedly, it means:
 *   - An interrupt was enabled that you forgot to write a handler for
 *   - An interrupt fired due to a hardware misconfiguration or a bug
 *
 * When debugging, you can set a breakpoint here to catch unexpected interrupts.
 * Then examine the stack and LR register to figure out which interrupt fired.
 *
 * "ax" in the .section directive means:
 *   a = allocatable (takes up space in the binary)
 *   x = executable (contains instructions, not just data)
 * %progbits means it contains actual program data (not zero-fill like .bss)
 */
  .section .text.Default_Handler,"ax",%progbits
Default_Handler:
Infinite_Loop:
  b Infinite_Loop    /* Spin here forever. The system is in an unknown state.
                        A watchdog timer (if configured) will eventually reset
                        the chip and give it another chance to run correctly. */
  .size Default_Handler, .-Default_Handler


/* ============================================================================
 * INTERRUPT VECTOR TABLE
 * ============================================================================
 *
 * WHAT IS THE VECTOR TABLE?
 * On ARM Cortex-M, when an interrupt or exception occurs, the hardware
 * automatically looks up a table of function pointers stored at the very
 * beginning of Flash memory (address 0x00000000). Each slot in the table
 * corresponds to a specific exception or interrupt source. The hardware reads
 * the address stored in that slot and jumps to it — this is the "handler".
 *
 * The table MUST be placed at address 0x00000000 (or at a location pointed
 * to by the VTOR register — Vector Table Offset Register — if you move it).
 * The linker script uses the ".isr_vector" section name to ensure this.
 *
 * TABLE LAYOUT:
 * Slot 0:  Initial Stack Pointer value (not a function — it's loaded into SP at reset)
 * Slot 1:  Reset Handler address (where execution begins)
 * Slot 2+: Exception and interrupt handler addresses
 *
 * Each entry is a 32-bit address (.word = 4 bytes).
 * Entries that say "0" are "reserved" by ST — those interrupt numbers don't
 * exist on this chip, so the slot is left empty (null pointer).
 *
 * "a" in .section means allocatable (included in the binary output).
 * %progbits means it contains real data.
 */
  .section .isr_vector,"a",%progbits
  .type g_pfnVectors, %object
  .size g_pfnVectors, .-g_pfnVectors

g_pfnVectors:

  /* ---- ARM Cortex-M Core Exceptions (positions 0–15) ---- */
  /* These are defined by the ARM architecture itself, not ST.
     Every Cortex-M chip has these same first 16 entries. */

  .word _estack                /* [0] Initial stack pointer value.
                                    NOT a handler address — the hardware loads
                                    this directly into SP (r13) on reset.
                                    _estack is the top of RAM. */

  .word Reset_Handler          /* [1] Reset exception — runs on power-on/reset.
                                    This is the entry point defined above. */

  .word NMI_Handler            /* [2] Non-Maskable Interrupt — cannot be
                                    disabled by software. Used for critical
                                    faults like clock failure. */

  .word HardFault_Handler      /* [3] Hard Fault — fires when a fault occurs
                                    that has no more specific handler, or when
                                    a fault occurs inside another fault handler.
                                    Common causes: null pointer dereference,
                                    stack overflow, bad instruction. */

  .word MemManage_Handler      /* [4] Memory Management Fault — MPU (Memory
                                    Protection Unit) access violation. Fires
                                    when code tries to access memory it's not
                                    allowed to (e.g., executing from RAM when
                                    the MPU forbids it). */

  .word BusFault_Handler       /* [5] Bus Fault — error on the AHB/APB bus
                                    during a memory access. Can be caused by
                                    accessing a non-existent peripheral address
                                    or bad DMA configuration. */

  .word UsageFault_Handler     /* [6] Usage Fault — undefined instruction,
                                    illegal unaligned access, invalid state
                                    transition (e.g., trying to switch to
                                    ARM mode from Thumb-only Cortex-M). */

  .word 0                      /* [7] Reserved by ARM spec */
  .word 0                      /* [8] Reserved by ARM spec */
  .word 0                      /* [9] Reserved by ARM spec */
  .word 0                      /* [10] Reserved by ARM spec */

  .word SVC_Handler            /* [11] SVCall (Supervisor Call) — triggered by
                                    the "svc" instruction. Used by RTOS kernels
                                    (like FreeRTOS) to request privileged
                                    operations from unprivileged task code. */

  .word DebugMon_Handler       /* [12] Debug Monitor — fires when a software
                                    breakpoint or watchpoint is hit while the
                                    debug monitor is active (as opposed to
                                    being halted by a hardware debugger). */

  .word 0                      /* [13] Reserved by ARM spec */

  .word PendSV_Handler         /* [14] PendSV (Pendable Service Call) — a
                                    software-triggerable, low-priority interrupt.
                                    FreeRTOS and other RTOSes use this for
                                    context switching between tasks, because it
                                    can be pended (deferred) and will run after
                                    all higher-priority interrupts complete. */

  .word SysTick_Handler        /* [15] SysTick — a simple 24-bit countdown
                                    timer built into the Cortex-M core.
                                    HAL uses this for the HAL_Delay() 1ms tick.
                                    FreeRTOS uses it for the scheduler tick. */


  /* ---- STM32F407-Specific Peripheral Interrupts (positions 16+) ----
   *
   * Everything from here on is specific to the STM32F407 chip design by ST.
   * These are IRQs (Interrupt Requests) from the on-chip peripherals.
   * The number in the comment is the IRQ number (position - 16).
   * In C code you reference these with enum values like USART1_IRQn.
   *
   * In your application code, you define a handler by simply writing a
   * function with the exact same name, e.g.:
   *
   *     void USART1_IRQHandler(void) {
   *         // handle received byte
   *     }
   *
   * Because these are declared .weak below, your version overrides the
   * default (which just spins forever in Default_Handler).
   */

  .word WWDG_IRQHandler        /* IRQ0:  Window Watchdog — a timer that resets
                                    the chip if your firmware "forgets" to pet
                                    it. Window = must be refreshed within a
                                    specific time window, not too early or late. */

  .word PVD_IRQHandler         /* IRQ1:  PVD (Programmable Voltage Detector) —
                                    fires when VDD supply voltage drops below
                                    a programmable threshold. Useful for
                                    detecting a dying battery before it causes
                                    data corruption. */

  .word TAMP_STAMP_IRQHandler  /* IRQ2:  Tamper detection + Timestamp via EXTI.
                                    RTC tamper pins detect physical tampering
                                    with the hardware. */

  .word RTC_WKUP_IRQHandler    /* IRQ3:  RTC (Real-Time Clock) Wakeup — wakes
                                    the chip from Stop/Standby low-power modes
                                    on a scheduled interval. */

  .word 0                      /* IRQ4:  Reserved (not used on STM32F407) */

  .word RCC_IRQHandler         /* IRQ5:  RCC (Reset and Clock Control) —
                                    clock security system interrupt. Fires if
                                    the external crystal oscillator fails so
                                    software can switch to the internal backup
                                    oscillator. */

  .word EXTI0_IRQHandler       /* IRQ6:  EXTI Line 0 — External Interrupt on
                                    GPIO pin 0 (PA0, PB0, PC0, etc.).
                                    Used to detect button presses, encoder
                                    pulses, or any digital signal edge. */

  .word EXTI1_IRQHandler       /* IRQ7:  EXTI Line 1 — GPIO pin 1 */
  .word EXTI2_IRQHandler       /* IRQ8:  EXTI Line 2 — GPIO pin 2 */
  .word EXTI3_IRQHandler       /* IRQ9:  EXTI Line 3 — GPIO pin 3 */
  .word EXTI4_IRQHandler       /* IRQ10: EXTI Line 4 — GPIO pin 4 */

  .word DMA1_Stream0_IRQHandler /* IRQ11: DMA1 Stream 0.
                                    DMA = Direct Memory Access. The DMA
                                    controller moves data between peripherals
                                    and RAM without involving the CPU, freeing
                                    the CPU to do other work. Each "stream"
                                    is an independent DMA channel.
                                    This fires when the transfer completes,
                                    or when a transfer error occurs. */

  .word DMA1_Stream1_IRQHandler /* IRQ12: DMA1 Stream 1 */
  .word DMA1_Stream2_IRQHandler /* IRQ13: DMA1 Stream 2 */
  .word DMA1_Stream3_IRQHandler /* IRQ14: DMA1 Stream 3 */
  .word DMA1_Stream4_IRQHandler /* IRQ15: DMA1 Stream 4 */
  .word DMA1_Stream5_IRQHandler /* IRQ16: DMA1 Stream 5 */
  .word DMA1_Stream6_IRQHandler /* IRQ17: DMA1 Stream 6 */

  .word ADC_IRQHandler         /* IRQ18: ADC (Analog-to-Digital Converter)
                                    global interrupt. The F407 has 3 ADCs.
                                    Fires on conversion complete, overrun,
                                    or injected channel end. */

  .word CAN1_TX_IRQHandler     /* IRQ19: CAN1 Transmit — CAN (Controller Area
                                    Network) is a robust serial protocol used
                                    in automotive and industrial systems.
                                    This fires when a CAN frame finishes
                                    transmitting (mailbox empty). */

  .word CAN1_RX0_IRQHandler    /* IRQ20: CAN1 Receive FIFO 0 — fires when a
                                    CAN frame is received into FIFO 0. */

  .word CAN1_RX1_IRQHandler    /* IRQ21: CAN1 Receive FIFO 1 */

  .word CAN1_SCE_IRQHandler    /* IRQ22: CAN1 Status Change / Error —
                                    fires on bus-off, error passive, or
                                    last error code changes. */

  .word EXTI9_5_IRQHandler     /* IRQ23: EXTI Lines 5–9 — GPIO pins 5,6,7,8,9
                                    share a single interrupt. Your handler must
                                    check the EXTI_PR register to determine
                                    which specific pin triggered it. */

  .word TIM1_BRK_TIM9_IRQHandler  /* IRQ24: TIM1 Break + TIM9 global.
                                    TIM1 is an "advanced" timer with PWM
                                    features. The Break input shuts down PWM
                                    outputs on a fault condition (e.g., overcurrent).
                                    TIM9 is a general-purpose timer. */

  .word TIM1_UP_TIM10_IRQHandler  /* IRQ25: TIM1 Update (counter overflow/underflow)
                                    + TIM10 global interrupt. */

  .word TIM1_TRG_COM_TIM11_IRQHandler /* IRQ26: TIM1 Trigger & Commutation
                                    (used in 3-phase motor control) + TIM11 global. */

  .word TIM1_CC_IRQHandler     /* IRQ27: TIM1 Capture/Compare — fires when
                                    a timer channel captures an input signal
                                    timestamp or matches an output compare value. */

  .word TIM2_IRQHandler        /* IRQ28: TIM2 global — 32-bit general purpose
                                    timer, useful for precise time measurement. */

  .word TIM3_IRQHandler        /* IRQ29: TIM3 global — 16-bit general purpose timer */
  .word TIM4_IRQHandler        /* IRQ30: TIM4 global — 16-bit general purpose timer */

  .word I2C1_EV_IRQHandler     /* IRQ31: I2C1 Event — I2C is a 2-wire serial
                                    bus (SDA + SCL) used for sensors, EEPROMs,
                                    displays, etc. The Event interrupt fires on
                                    address match, byte received/sent, STOP detected. */

  .word I2C1_ER_IRQHandler     /* IRQ32: I2C1 Error — bus error, arbitration
                                    loss, NACK received, etc. */

  .word I2C2_EV_IRQHandler     /* IRQ33: I2C2 Event */
  .word I2C2_ER_IRQHandler     /* IRQ34: I2C2 Error */

  .word SPI1_IRQHandler        /* IRQ35: SPI1 global — SPI (Serial Peripheral
                                    Interface) is a fast 4-wire bus (MOSI, MISO,
                                    SCK, CS) used for SD cards, displays,
                                    ADCs, sensors, etc. */

  .word SPI2_IRQHandler        /* IRQ36: SPI2 global */

  .word USART1_IRQHandler      /* IRQ37: USART1 — Universal Synchronous/
                                    Asynchronous Receiver-Transmitter. This is
                                    your standard serial/UART. Fires on byte
                                    received, transmit buffer empty, etc.
                                    Commonly used for debug output or talking
                                    to a PC over USB-serial. */

  .word USART2_IRQHandler      /* IRQ38: USART2 global */
  .word USART3_IRQHandler      /* IRQ39: USART3 global */

  .word EXTI15_10_IRQHandler   /* IRQ40: EXTI Lines 10–15 — GPIO pins 10–15.
                                    Same shared-interrupt situation as EXTI9_5. */

  .word RTC_Alarm_IRQHandler   /* IRQ41: RTC Alarm A or B through EXTI —
                                    Wake up / trigger at a specific date/time. */

  .word OTG_FS_WKUP_IRQHandler /* IRQ42: USB OTG Full-Speed Wakeup — wakes
                                    the chip from low-power mode when USB
                                    activity is detected. */

  .word TIM8_BRK_TIM12_IRQHandler  /* IRQ43: TIM8 Break + TIM12 global */
  .word TIM8_UP_TIM13_IRQHandler   /* IRQ44: TIM8 Update + TIM13 global */
  .word TIM8_TRG_COM_TIM14_IRQHandler /* IRQ45: TIM8 Trigger/Commutation + TIM14 */
  .word TIM8_CC_IRQHandler     /* IRQ46: TIM8 Capture/Compare */
  .word DMA1_Stream7_IRQHandler /* IRQ47: DMA1 Stream 7 */

  .word FSMC_IRQHandler        /* IRQ48: FSMC (Flexible Static Memory
                                    Controller) — used to interface with
                                    external parallel memories like SRAM,
                                    NOR Flash, and LCD controllers. */

  .word SDIO_IRQHandler        /* IRQ49: SDIO — SD card interface interrupt.
                                    Fires on transfer complete, FIFO errors, etc. */

  .word TIM5_IRQHandler        /* IRQ50: TIM5 global — 32-bit general purpose timer */
  .word SPI3_IRQHandler        /* IRQ51: SPI3 global */

  .word UART4_IRQHandler       /* IRQ52: UART4 global — Note: UART (not USART).
                                    UARTs lack the synchronous clock line that
                                    USARTs have. Still async serial. */

  .word UART5_IRQHandler       /* IRQ53: UART5 global */

  .word TIM6_DAC_IRQHandler    /* IRQ54: TIM6 global + DAC underrun error.
                                    TIM6 is often used as the trigger source
                                    for the DAC (Digital-to-Analog Converter).
                                    Underrun = DAC ran out of data to output. */

  .word TIM7_IRQHandler        /* IRQ55: TIM7 global — basic timer, often used
                                    as a timebase for DAC or periodic callbacks */

  .word DMA2_Stream0_IRQHandler /* IRQ56: DMA2 Stream 0 */
  .word DMA2_Stream1_IRQHandler /* IRQ57: DMA2 Stream 1 */
  .word DMA2_Stream2_IRQHandler /* IRQ58: DMA2 Stream 2 */
  .word DMA2_Stream3_IRQHandler /* IRQ59: DMA2 Stream 3 */
  .word DMA2_Stream4_IRQHandler /* IRQ60: DMA2 Stream 4 */

  .word ETH_IRQHandler         /* IRQ61: Ethernet MAC global interrupt —
                                    the STM32F407 has a built-in 10/100 Mbps
                                    Ethernet MAC (Media Access Controller).
                                    Fires on frame received/sent, etc. */

  .word ETH_WKUP_IRQHandler    /* IRQ62: Ethernet Wakeup through EXTI —
                                    wake from low-power mode on network activity */

  .word CAN2_TX_IRQHandler     /* IRQ63: CAN2 Transmit */
  .word CAN2_RX0_IRQHandler    /* IRQ64: CAN2 Receive FIFO 0 */
  .word CAN2_RX1_IRQHandler    /* IRQ65: CAN2 Receive FIFO 1 */
  .word CAN2_SCE_IRQHandler    /* IRQ66: CAN2 Status/Error */

  .word OTG_FS_IRQHandler      /* IRQ67: USB OTG Full-Speed global interrupt —
                                    the STM32F407 has a built-in USB 2.0
                                    Full-Speed (12 Mbps) OTG controller.
                                    OTG = On-The-Go (can be host or device). */

  .word DMA2_Stream5_IRQHandler /* IRQ68: DMA2 Stream 5 */
  .word DMA2_Stream6_IRQHandler /* IRQ69: DMA2 Stream 6 */
  .word DMA2_Stream7_IRQHandler /* IRQ70: DMA2 Stream 7 */

  .word USART6_IRQHandler      /* IRQ71: USART6 global */

  .word I2C3_EV_IRQHandler     /* IRQ72: I2C3 Event */
  .word I2C3_ER_IRQHandler     /* IRQ73: I2C3 Error */

  .word OTG_HS_EP1_OUT_IRQHandler /* IRQ74: USB OTG High-Speed Endpoint 1 OUT —
                                    the F407 also has a USB HS (480 Mbps)
                                    controller (though it typically needs an
                                    external HS PHY chip). This handles data
                                    flowing OUT from host to device on EP1. */

  .word OTG_HS_EP1_IN_IRQHandler  /* IRQ75: USB OTG HS Endpoint 1 IN —
                                    data flowing IN from device to host on EP1. */

  .word OTG_HS_WKUP_IRQHandler /* IRQ76: USB OTG HS Wakeup through EXTI */
  .word OTG_HS_IRQHandler      /* IRQ77: USB OTG HS global interrupt */

  .word DCMI_IRQHandler        /* IRQ78: DCMI (Digital Camera Interface) —
                                    parallel camera interface for connecting
                                    OV7670-style camera modules directly. */

  .word CRYP_IRQHandler        /* IRQ79: Cryptographic processor global —
                                    hardware AES, DES, Triple-DES acceleration. */

  .word HASH_RNG_IRQHandler    /* IRQ80: Hash (SHA-1, MD5) + RNG (Random Number
                                    Generator) global interrupt. The hardware
                                    RNG uses analog noise to generate true
                                    random numbers — useful for cryptography. */

  .word FPU_IRQHandler         /* IRQ81: FPU (Floating-Point Unit) global —
                                    fires on FPU exceptions like divide-by-zero,
                                    overflow, underflow, or invalid operation,
                                    if those exception traps are enabled. */

  /* Slots 82–87: Reserved by ST (these IRQ numbers don't exist on F407) */
  .word 0
  .word 0
  .word 0
  .word 0
  .word 0
  .word 0

  .word LCD_TFT_IRQHandler     /* IRQ88: LTDC (LCD-TFT Display Controller) —
                                    the F407 has a hardware layer compositor
                                    for driving RGB TFT displays. This fires
                                    on frame sync, line events, etc. */

  .word LCD_TFT_1_IRQHandler   /* IRQ89: LTDC Error interrupt — fires on FIFO
                                    underrun or transfer error in the display
                                    controller. */


/* ============================================================================
 * WEAK ALIASES FOR ALL INTERRUPT HANDLERS
 * ============================================================================
 *
 * WHAT IS A WEAK ALIAS?
 * The directives below do two things for each handler:
 *
 *   .weak SomeHandler
 *     Makes SomeHandler a "weak" symbol. If your application code defines
 *     a function with the exact same name, the linker uses YOUR version and
 *     ignores this one. If you DON'T define it, the linker keeps this one.
 *
 *   .thumb_set SomeHandler, Default_Handler
 *     Makes SomeHandler an alias (another name) for Default_Handler.
 *     Combined with .weak, this means: "by default, SomeHandler points to
 *     Default_Handler (the infinite loop), but any user-defined function
 *     called SomeHandler will override this."
 *
 * THE PRACTICAL RESULT:
 * You only need to write handlers for interrupts you actually use.
 * All others silently redirect to the infinite loop, making debugging easier
 * (you can set a breakpoint in Default_Handler to catch any unhandled IRQ).
 *
 * EXAMPLE:
 * If you want to handle UART1 bytes:
 *
 *   void USART1_IRQHandler(void) {     // exact name match required!
 *       char c = USART1->DR;           // read the received byte
 *       my_buffer_push(c);
 *   }
 *
 * The linker sees your strong definition and uses it instead of the
 * weak alias to Default_Handler below.
 */

  /* Core ARM exception handlers */
	.weak	NMI_Handler
	.thumb_set NMI_Handler,Default_Handler

	.weak	HardFault_Handler
	.thumb_set HardFault_Handler,Default_Handler

	.weak	MemManage_Handler
	.thumb_set MemManage_Handler,Default_Handler

	.weak	BusFault_Handler
	.thumb_set BusFault_Handler,Default_Handler

	.weak	UsageFault_Handler
	.thumb_set UsageFault_Handler,Default_Handler

	.weak	SVC_Handler
	.thumb_set SVC_Handler,Default_Handler

	.weak	DebugMon_Handler
	.thumb_set DebugMon_Handler,Default_Handler

	.weak	PendSV_Handler
	.thumb_set PendSV_Handler,Default_Handler

	.weak	SysTick_Handler
	.thumb_set SysTick_Handler,Default_Handler

	/* STM32F407 peripheral interrupt handlers */
	.weak	WWDG_IRQHandler
	.thumb_set WWDG_IRQHandler,Default_Handler

	.weak	PVD_IRQHandler
	.thumb_set PVD_IRQHandler,Default_Handler

	.weak	TAMP_STAMP_IRQHandler
	.thumb_set TAMP_STAMP_IRQHandler,Default_Handler

	.weak	RTC_WKUP_IRQHandler
	.thumb_set RTC_WKUP_IRQHandler,Default_Handler

	.weak	RCC_IRQHandler
	.thumb_set RCC_IRQHandler,Default_Handler

	.weak	EXTI0_IRQHandler
	.thumb_set EXTI0_IRQHandler,Default_Handler

	.weak	EXTI1_IRQHandler
	.thumb_set EXTI1_IRQHandler,Default_Handler

	.weak	EXTI2_IRQHandler
	.thumb_set EXTI2_IRQHandler,Default_Handler

	.weak	EXTI3_IRQHandler
	.thumb_set EXTI3_IRQHandler,Default_Handler

	.weak	EXTI4_IRQHandler
	.thumb_set EXTI4_IRQHandler,Default_Handler

	.weak	DMA1_Stream0_IRQHandler
	.thumb_set DMA1_Stream0_IRQHandler,Default_Handler

	.weak	DMA1_Stream1_IRQHandler
	.thumb_set DMA1_Stream1_IRQHandler,Default_Handler

	.weak	DMA1_Stream2_IRQHandler
	.thumb_set DMA1_Stream2_IRQHandler,Default_Handler

	.weak	DMA1_Stream3_IRQHandler
	.thumb_set DMA1_Stream3_IRQHandler,Default_Handler

	.weak	DMA1_Stream4_IRQHandler
	.thumb_set DMA1_Stream4_IRQHandler,Default_Handler

	.weak	DMA1_Stream5_IRQHandler
	.thumb_set DMA1_Stream5_IRQHandler,Default_Handler

	.weak	DMA1_Stream6_IRQHandler
	.thumb_set DMA1_Stream6_IRQHandler,Default_Handler

	.weak	ADC_IRQHandler
	.thumb_set ADC_IRQHandler,Default_Handler

	.weak	CAN1_TX_IRQHandler
	.thumb_set CAN1_TX_IRQHandler,Default_Handler

	.weak	CAN1_RX0_IRQHandler
	.thumb_set CAN1_RX0_IRQHandler,Default_Handler

	.weak	CAN1_RX1_IRQHandler
	.thumb_set CAN1_RX1_IRQHandler,Default_Handler

	.weak	CAN1_SCE_IRQHandler
	.thumb_set CAN1_SCE_IRQHandler,Default_Handler

	.weak	EXTI9_5_IRQHandler
	.thumb_set EXTI9_5_IRQHandler,Default_Handler

	.weak	TIM1_BRK_TIM9_IRQHandler
	.thumb_set TIM1_BRK_TIM9_IRQHandler,Default_Handler

	.weak	TIM1_UP_TIM10_IRQHandler
	.thumb_set TIM1_UP_TIM10_IRQHandler,Default_Handler

	.weak	TIM1_TRG_COM_TIM11_IRQHandler
	.thumb_set TIM1_TRG_COM_TIM11_IRQHandler,Default_Handler

	.weak	TIM1_CC_IRQHandler
	.thumb_set TIM1_CC_IRQHandler,Default_Handler

	.weak	TIM2_IRQHandler
	.thumb_set TIM2_IRQHandler,Default_Handler

	.weak	TIM3_IRQHandler
	.thumb_set TIM3_IRQHandler,Default_Handler

	.weak	TIM4_IRQHandler
	.thumb_set TIM4_IRQHandler,Default_Handler

	.weak	I2C1_EV_IRQHandler
	.thumb_set I2C1_EV_IRQHandler,Default_Handler

	.weak	I2C1_ER_IRQHandler
	.thumb_set I2C1_ER_IRQHandler,Default_Handler

	.weak	I2C2_EV_IRQHandler
	.thumb_set I2C2_EV_IRQHandler,Default_Handler

	.weak	I2C2_ER_IRQHandler
	.thumb_set I2C2_ER_IRQHandler,Default_Handler

	.weak	SPI1_IRQHandler
	.thumb_set SPI1_IRQHandler,Default_Handler

	.weak	SPI2_IRQHandler
	.thumb_set SPI2_IRQHandler,Default_Handler

	.weak	USART1_IRQHandler
	.thumb_set USART1_IRQHandler,Default_Handler

	.weak	USART2_IRQHandler
	.thumb_set USART2_IRQHandler,Default_Handler

	.weak	USART3_IRQHandler
	.thumb_set USART3_IRQHandler,Default_Handler

	.weak	EXTI15_10_IRQHandler
	.thumb_set EXTI15_10_IRQHandler,Default_Handler

	.weak	RTC_Alarm_IRQHandler
	.thumb_set RTC_Alarm_IRQHandler,Default_Handler

	.weak	OTG_FS_WKUP_IRQHandler
	.thumb_set OTG_FS_WKUP_IRQHandler,Default_Handler

	.weak	TIM8_BRK_TIM12_IRQHandler
	.thumb_set TIM8_BRK_TIM12_IRQHandler,Default_Handler

	.weak	TIM8_UP_TIM13_IRQHandler
	.thumb_set TIM8_UP_TIM13_IRQHandler,Default_Handler

	.weak	TIM8_TRG_COM_TIM14_IRQHandler
	.thumb_set TIM8_TRG_COM_TIM14_IRQHandler,Default_Handler

	.weak	TIM8_CC_IRQHandler
	.thumb_set TIM8_CC_IRQHandler,Default_Handler

	.weak	DMA1_Stream7_IRQHandler
	.thumb_set DMA1_Stream7_IRQHandler,Default_Handler

	.weak	FSMC_IRQHandler
	.thumb_set FSMC_IRQHandler,Default_Handler

	.weak	SDIO_IRQHandler
	.thumb_set SDIO_IRQHandler,Default_Handler

	.weak	TIM5_IRQHandler
	.thumb_set TIM5_IRQHandler,Default_Handler

	.weak	SPI3_IRQHandler
	.thumb_set SPI3_IRQHandler,Default_Handler

	.weak	UART4_IRQHandler
	.thumb_set UART4_IRQHandler,Default_Handler

	.weak	UART5_IRQHandler
	.thumb_set UART5_IRQHandler,Default_Handler

	.weak	TIM6_DAC_IRQHandler
	.thumb_set TIM6_DAC_IRQHandler,Default_Handler

	.weak	TIM7_IRQHandler
	.thumb_set TIM7_IRQHandler,Default_Handler

	.weak	DMA2_Stream0_IRQHandler
	.thumb_set DMA2_Stream0_IRQHandler,Default_Handler

	.weak	DMA2_Stream1_IRQHandler
	.thumb_set DMA2_Stream1_IRQHandler,Default_Handler

	.weak	DMA2_Stream2_IRQHandler
	.thumb_set DMA2_Stream2_IRQHandler,Default_Handler

	.weak	DMA2_Stream3_IRQHandler
	.thumb_set DMA2_Stream3_IRQHandler,Default_Handler

	.weak	DMA2_Stream4_IRQHandler
	.thumb_set DMA2_Stream4_IRQHandler,Default_Handler

	.weak	ETH_IRQHandler
	.thumb_set ETH_IRQHandler,Default_Handler

	.weak	ETH_WKUP_IRQHandler
	.thumb_set ETH_WKUP_IRQHandler,Default_Handler

	.weak	CAN2_TX_IRQHandler
	.thumb_set CAN2_TX_IRQHandler,Default_Handler

	.weak	CAN2_RX0_IRQHandler
	.thumb_set CAN2_RX0_IRQHandler,Default_Handler

	.weak	CAN2_RX1_IRQHandler
	.thumb_set CAN2_RX1_IRQHandler,Default_Handler

	.weak	CAN2_SCE_IRQHandler
	.thumb_set CAN2_SCE_IRQHandler,Default_Handler

	.weak	OTG_FS_IRQHandler
	.thumb_set OTG_FS_IRQHandler,Default_Handler

	.weak	DMA2_Stream5_IRQHandler
	.thumb_set DMA2_Stream5_IRQHandler,Default_Handler

	.weak	DMA2_Stream6_IRQHandler
	.thumb_set DMA2_Stream6_IRQHandler,Default_Handler

	.weak	DMA2_Stream7_IRQHandler
	.thumb_set DMA2_Stream7_IRQHandler,Default_Handler

	.weak	USART6_IRQHandler
	.thumb_set USART6_IRQHandler,Default_Handler

	.weak	I2C3_EV_IRQHandler
	.thumb_set I2C3_EV_IRQHandler,Default_Handler

	.weak	I2C3_ER_IRQHandler
	.thumb_set I2C3_ER_IRQHandler,Default_Handler

	.weak	OTG_HS_EP1_OUT_IRQHandler
	.thumb_set OTG_HS_EP1_OUT_IRQHandler,Default_Handler

	.weak	OTG_HS_EP1_IN_IRQHandler
	.thumb_set OTG_HS_EP1_IN_IRQHandler,Default_Handler

	.weak	OTG_HS_WKUP_IRQHandler
	.thumb_set OTG_HS_WKUP_IRQHandler,Default_Handler

	.weak	OTG_HS_IRQHandler
	.thumb_set OTG_HS_IRQHandler,Default_Handler

	.weak	DCMI_IRQHandler
	.thumb_set DCMI_IRQHandler,Default_Handler

	.weak	CRYP_IRQHandler
	.thumb_set CRYP_IRQHandler,Default_Handler

	.weak	HASH_RNG_IRQHandler
	.thumb_set HASH_RNG_IRQHandler,Default_Handler

	.weak	FPU_IRQHandler
	.thumb_set FPU_IRQHandler,Default_Handler

	.weak	LCD_TFT_IRQHandler
	.thumb_set LCD_TFT_IRQHandler,Default_Handler

	.weak	LCD_TFT_1_IRQHandler
	.thumb_set LCD_TFT_1_IRQHandler,Default_Handler

	/* SystemInit is also declared weak here. This means if you don't provide
	   your own SystemInit() (e.g., if you're not using ST's HAL/CMSIS), the
	   linker won't complain — it just won't call anything for clock setup.
	   Normally you DO want SystemInit() from system_stm32f4xx.c to run. */
	.weak	SystemInit

/************************ (C) COPYRIGHT STMicroelectonics *****END OF FILE****/
